# Custom Language File for Launcher Customizer

[ejs.app]
title = "Eclipse SMP Launcher"

[ejs.landing]
mediaDiscordURL = "https://discord.gg/xZBHEWTbD5"

[ejs.settings]
sourceGithubLink = "https://github.com/edouard57/eclipsesmp"
supportLink = "https://github.com/edouard57/eclipsesmp/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR ECLIPSE SMP"
welcomeDescription = "Eclipse SMP est un serveur survie communautaire. Ce launcher installe et maintient a jour automatiquement Fabric et le pack de mods d'optimisation, pour que tu n'aies qu'a cliquer sur Jouer."
welcomeDescCTA = "Tu es a quelques clics d'Eclipse SMP."
